FROM golang:1.25-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build -o web ./cmd/web

FROM alpine:latest
RUN apk add --no-cache curl
WORKDIR /app
COPY --from=builder /app/web .
EXPOSE 3000
ENV HCI_WEB_PORT=3000
CMD ["./web"]
